version: '3'
services:
  couchdb:
    image: couchdb:3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - ./couchdb/data:/opt/couchdb/data
      - ./couchdb/etc:/opt/couchdb/etc/local.d
    ports:
      - 127.0.0.1:5984:5984
    labels:
      - traefik.enable=true
      - traefik.http.services.couchdb.loadbalancer.server.port=5984
      - traefik.http.routers.couchdb.rule=PathPrefix(`/couchdb`)
      - traefik.http.routers.couchdb.middlewares=couchdb_strip_prefix@docker
      - traefik.http.middlewares.couchdb_strip_prefix.stripprefix.prefixes=/couchdb

  main:
    profiles:
      - staging
    build: main
    init: true
    environment:
      - TZ=Europe/Berlin
      - NODE_CONFIG_ENV=staging
      - PORT=3000
    volumes:
      - ./main/config:/opt/app/config
      - ./main/database:/opt/app/database
      - ./main/server/website/plugins:/opt/app/server/website/plugins
    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=3000
      - 'traefik.http.routers.app.rule=PathPrefix(`/`)'

  traefik:
    profiles:
      - staging
    init: true
    restart: unless-stopped
    image: traefik:v2.10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:80
      - 8080:8080
    command:
      - --api.insecure=true
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --providers.docker
      - --providers.docker.exposedByDefault=false
